[package]
name = "wagmi"
version = "0.1.0"
edition = "2021"

[features]
wasm_debug = []

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
paste = "1.0.15"
[dev-dependencies]
pretty_assertions = "1"
